<?php
/**
 * @file
 *
 * Hook implementations and functions for the Reviews module.
 */

/**
 * Implements hook_node_info().
 */
function reviews_node_info() {
  return array(
    'book_review' => array(
      'name' => t('Book Review'),
      'base' => 'reviews',
      'description' => t('Provides the Book Review content type and UI.'),
      'has_title' => TRUE,
      'title_label' => t('Book Title'),
      'locked' => TRUE,
    ),
  );
}

/**
 * Implements hook_form().
 */
function reviews_form($node, &$form_state) {
  $type = node_type_get_type($node);
  
  $form = array();
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#default_value' => empty($node->title) ? '' : $node->title,
    '#required' => TRUE,
    '#weight' => -10,
  );
  
  if (!empty($form_state['values']['field_rating'][LANGUAGE_NONE][0]['value'])) {
    $display = $form_state['values']['field_rating'][LANGUAGE_NONE][0]['value'];
  }
  elseif (!empty($node->field_rating[LANGUAGE_NONE][0]['value'])) {
    $display = $node->field_rating[LANGUAGE_NONE][0]['value'];
  }
  else {
    $display = t('Not rated.');
  }
  
  $form['rating_display'] = array(
    '#type' => 'item',
    '#markup' => $display,
    '#title' => t('Current Rating'),
    '#prefix' => '<div id="rating-display">',
    '#suffix' => '</div>',
  );
  
  return $form;
}

/**
 * Implements hook_node_view().
 */
function reviews_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'book_review') {
    $node->title = 'Review: ' . $node->title;
  
    if ($view_mode == 'full') {
      drupal_set_title($node->title);
    }
  }
}

/**
 * Implements hook_block_info().
 */
function reviews_block_info() {
  return array(
    'recent_reviews' => array(
      'info' => t('Recent Book Reviews'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function reviews_block_view($delta = '') {
  $block = array();
  
  if ($delta == 'recent_reviews' && user_access('access content')) {
    $block['subject'] = t('Recent Book Reviews');
    $block['content'] = reviews_recent_reviews_content();
  }
  
  return $block;
}

/**
 * Return a renderable array of recent book reviews.
 */
function reviews_recent_reviews_content() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node');
  $query->propertyCondition('type', 'book_review');
  $query->propertyOrderBy('created', 'DESC');
  $query->range(0, 5);
  $results = $query->execute();
  
  $nodes = array();
  if (!empty($results['node'])) {
    $nodes = node_load_multiple(array_keys($results['node']));
  }
  
  return node_title_list($nodes);
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function reviews_form_book_review_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_rating'][LANGUAGE_NONE][0]['value']['#ajax'] = array(
    'callback' => 'reviews_rating_js',
    'wrapper' => 'rating-display',
  );
}


/**
 * AJAX callback for rating display.
 */
function reviews_rating_js($form, $form_state) {
  return $form['rating_display'];
}